services:

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis
    env_file:
      - .env

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A worstShop worker --loglevel=INFO
    volumes:
      - .:/worstshop
    depends_on:
      - redis
    env_file:
      - .env

  stripe:
    image: stripe/stripe-cli:latest
    command: listen --forward-to http://web:8000/webhook/stripe/
    environment:
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate  && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/worstshop
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
